### ISSUE TITLE
Need a way to specify where the log file is generated

### ISSUE THREAD

**Issue by dbarrous** [HERMES-SOC/hermes_core#21]
There should be a way to specify the directory which the log file should be generated into. This could cause issues when trying to write to read-only sources such as in an AWS Lambda that can only write things to `/tmp/`

**Comment by ehsteve** [comment]
This is a difficult to tackle by making changes to `hermes_core`. The location of the log file is specified in our configrc file. This is the default for all users so we can't change it to `\tmp` because someone on a Mac would get an error. It is possible to make changes to the configuration inside a python session but the log file is generated on import of `hermes_core` so that does not help. Before importing we could make changes to the config but the config file needs to be placed where it is expected. Currently that is set by [Appdirs](https://github.com/sunpy/sunpy/blob/main/sunpy/extern/appdirs.py) which supports many operating systems but does not consider aws lambda.

I did a little research and could we not just do what is recommended in this [Stackoverflow question](https://stackoverflow.com/questions/48364250/write-to-tmp-directory-in-aws-lambda-with-python)? Just change into the tmp directory making it that the working directory. Then we would not have to make any changes to `hermes_core`.

**Comment by ehsteve** [comment]
@dbarrous This is resolved right?
